import { defineStore } from "pinia";
import { toTypedSchema } from '@vee-validate/yup';
import * as yup from 'yup';

interface State<T> {
  priceTypeList: { value: string, key: string }[];
  sizes: string[];
  productTypes: string[];
  formValidation: T;
  initialValues: any;
  productKeys: string[];
  pricesByRole: { [key: string]: string[] }
}

export const useProductStore = defineStore('product', {
  state: (): State<typeof formValidation> => {
    const priceTypeList = [
      { value: 'Internet', key: 'internet' },
      { value: 'MAP', key: 'map' },
      { value: 'MSRP', key: 'msrp' },
      { value: 'Group', key: 'group' },
      { value: 'Dealer', key: 'dealer' },
      { value: 'Distributor', key: 'distributor' },
      { value: 'Landscape', key: 'landscape' },
      { value: 'Master Distributor', key: 'master_distributor' },
    ];
    const sizes = [
      '36"',
      '30"',
      '24"',
      '48"',
      '60"',
      '72"',
      '18"',
      '84"',
      '96"',
      '42"',
      '29"',
      '24"x12"',
      '39"',
      '28"',
      '31"',
      '27"',
      '12"',
      '38"',
      '36"x12"',
      '48"x12"',
      '96"x12"',
      '84"x12"',
      '72"x12"',
      '60"x12"',
      '32"x18"',
      '36"x24"',
      '120"',
      '30"x12"',
      '30"x6"',
      '36"x6"',
      '54"',
      '24"x6"',
      '8"',
      '108"',
      '37"',
      '33"',
      '66"',
      '42"x12"',
      '12"x60"',
      '12"x48"',
      '30"x30"',
      '48"24',
      '12"x24"',
    ];
    const productTypes = ['VARIABLE', 'SIMPLE'];
    const formValidation = toTypedSchema(
      yup.object({
        collection_id: yup.number().nullable(),
        name: yup.string().min(2).required(),
        sku: yup.string().min(2).required(),
        product_type: yup.string().required(),
        burner_shape: yup.string().nullable(),
        compatible_canvas_cover: yup.string().nullable(),
        compatible_bullet_burner: yup.string().nullable(),
        compatible_glass_wind_guard: yup.string().nullable(),
        access_door: yup.boolean().nullable(),
        category_id: yup.number().nullable(),
        shape_id: yup.number().nullable(),
        product_serial_base: yup.string().nullable(),
        published: yup.boolean(),
        enabled: yup.boolean(),
        company_division: yup.string().nullable(),
        short_description: yup.string().nullable(),
        description: yup.string().nullable(),
        website_link: yup.string().nullable(),
      }),
    );

    const initialValues = {
      name: '',
      sku: '',
      productType: '',
      product_type: 'VARIABLE',
      burnerShape: '',
      compatibleCanvasCover: '',
      compatibleBulletBurner: '',
      compatibleGlassWindGuard: '',
      accessDoor: false,
      access_door: false,
      productSerialBase: '',
      published: false,
      enabled: false,
      companyDivision: '',
      shortDescription: '',
      description: '',
      websiteLink: '',
    }

    const productKeys = [
      'id',
      'sku',
      'product_type',
      'burner_shape',
      'compatible_canvas_cover',
      'compatible_bullet_burner',
      'compatible_glass_wind_guard',
      'access_door',
      'collection_id',
      'category_id',
      'shape_id',
      'product_serial_base',
      'certifications',
      'published',
      'enabled',
      'created_by',
      'updated_by',
      'company_division',
      'updated_at',
      'created_at',
      'name',
      'short_description',
      'description',
      'dealer_prices',
      'distributor_prices',
      'group_prices',
      'internet_prices',
      'landscape_prices',
      'map_prices',
      'master_distributor_prices',
      'msrp_prices',
      'images',
      'website_link',
    ];

    // const formValidation = toTypedSchema(
    //   yup.object({
    //     collection_id: yup.number().nullable(),
    //     name: yup.string().min(2).required(),
    //     sku: yup.string().min(2).required(),
    //     upc_codes: yup.string().nullable(),
    //     encoded_upc_codes: yup.string().nullable(),
    //     product_type: yup.string().required(),
    //     product_length: yup.string().nullable(),
    //     product_diameter: yup.string().nullable(),
    //     product_width: yup.string().nullable(),
    //     product_height: yup.string().nullable(),
    //     base_length: yup.string().nullable(),
    //     base_diameter: yup.string().nullable(),
    //     base_width: yup.string().nullable(),
    //     base_opening: yup.string().nullable(),
    //     toe_kick: yup.string().nullable(),
    //     soil_usage: yup.string().nullable(),
    //     scupper_width: yup.string().nullable(),
    //     scupper_inlet_opening: yup.string().nullable(),
    //     gpm: yup.string().nullable(),
    //     fire_glass: yup.string().nullable(),
    //     ba_length: yup.string().nullable(),
    //     ba_diameter: yup.string().nullable(),
    //     ba_width: yup.string().nullable(),
    //     ba_depth: yup.string().nullable(),
    //     burner_shape: yup.string().nullable(),
    //     burner_length: yup.string().nullable(),
    //     burner_diameter: yup.string().nullable(),
    //     compatible_canvas_cover: yup.string().nullable(),
    //     compatible_bullet_burner: yup.string().nullable(),
    //     compatible_glass_wind_guard: yup.string().nullable(),
    //     access_door: yup.boolean(),
    //     category_id: yup.number().nullable(),
    //     shape_id: yup.number().nullable(),
    //     material_id: yup.number().nullable(),
    //     color_id: yup.number().nullable(),
    //     ignition_id: yup.number().nullable(),
    //     gas_id: yup.number().nullable(),
    //     product_serial_base: yup.string().nullable(),
    //     base_color_id: yup.number().nullable(),
    //     base_material_id: yup.number().nullable(),
    //     published: yup.boolean(),
    //     enabled: yup.boolean(),
    //     company_division: yup.string().nullable(),
    //     short_description: yup.string().nullable(),
    //     description: yup.string().nullable(),
    //     website_link: yup.string().nullable(),
    //   }),
    // );

    // const initialValues = {
    //   name: '',
    //   sku: '',
    //   upcCodes: '',
    //   encodedUpcCodes: '',
    //   productType: '',
    //   productLength: '',
    //   productDiameter: '',
    //   productWidth: '',
    //   productHeight: '',
    //   baseLength: '',
    //   baseDiameter: '',
    //   baseWidth: '',
    //   baseOpening: '',
    //   toeKick: '',
    //   soilUsage: '',
    //   scupperWidth: '',
    //   scupperInletOpening: '',
    //   gpm: '',
    //   fireGlass: '',
    //   baLength: '',
    //   baDiameter: '',
    //   baWidth: '',
    //   baDepth: '',
    //   burnerShape: '',
    //   burnerLength: '',
    //   burnerDiameter: '',
    //   compatibleCanvasCover: '',
    //   compatibleBulletBurner: '',
    //   compatibleGlassWindGuard: '',
    //   accessDoor: false,
    //   productSerialBase: '',
    //   published: false,
    //   enabled: false,
    //   companyDivision: '',
    //   shortDescription: '',
    //   description: '',
    //   websiteLink: '',
    // }

    // const productKeys = [
    //   'id',
    //   'sku',
    //   'upc_codes',
    //   'encoded_upc_codes',
    //   'product_type',
    //   'product_length',
    //   'product_diameter',
    //   'product_width',
    //   'product_height',
    //   'base_length',
    //   'base_diameter',
    //   'base_width',
    //   'base_opening',
    //   'toe_kick',
    //   'soil_usage',
    //   'scupper_width',
    //   'scupper_inlet_opening',
    //   'gpm',
    //   'fire_glass',
    //   'ba_length',
    //   'ba_diameter',
    //   'ba_width',
    //   'ba_depth',
    //   'burner_shape',
    //   'burner_length',
    //   'burner_diameter',
    //   'compatible_canvas_cover',
    //   'compatible_bullet_burner',
    //   'compatible_glass_wind_guard',
    //   'access_door',
    //   'parent_id',
    //   'collection_id',
    //   'category_id',
    //   'shape_id',
    //   'material_id',
    //   'color_id',
    //   'ignition_id',
    //   'gas_id',
    //   'product_serial_base',
    //   'certifications',
    //   'base_color_id',
    //   'base_material_id',
    //   'published',
    //   'enabled',
    //   'created_by',
    //   'updated_by',
    //   'company_division',
    //   'updated_at',
    //   'created_at',
    //   'name',
    //   'short_description',
    //   'description',
    //   'dealer_prices',
    //   'distributor_prices',
    //   'group_prices',
    //   'internet_prices',
    //   'landscape_prices',
    //   'map_prices',
    //   'master_distributor_prices',
    //   'msrp_prices',
    //   'images',
    //   'website_link',
    // ];

    const pricesByRole = {
      USER: ['msrp'],
      GUEST: ['msrp'],
      GROUP: ['group', 'map', 'msrp'],
      LANDSCAPE: ['landscape', 'map', 'msrp'],
      INTERNET: ['internet', 'map', 'msrp'],
      ECOMMERCE: ['map', 'msrp'],
      DEALER: ['dealer', 'map', 'msrp'],
      DISTRIBUTOR: ['distributor', 'map', 'msrp'],
      MASTER_DISTRIBUTOR: ['master_distributor', 'msrp', 'map'],
      MANAGER: ['msrp', 'map', 'internet', 'dealer', 'distributor', 'group', 'landscape', 'master_distributor'],
      ADMIN: ['msrp', 'map', 'internet', 'dealer', 'distributor', 'group', 'landscape', 'master_distributor'],
      SALES: ['msrp', 'map', 'internet', 'dealer', 'distributor', 'group', 'landscape', 'master_distributor'],
    }

    return {
      priceTypeList,
      sizes,
      formValidation,
      initialValues,
      productKeys,
      pricesByRole,
      productTypes,
    }
  },
  actions: {
    allowedPrices(userRole: string) {
      return this.pricesByRole[userRole];
    }
  },
  getters: {
  },
});
